version: '3.8'

services:
  # Development Service
  app-dev:
    build:
      context: .
    volumes:
      - .:/usr/src/app:Z
    ports:
      - "4000:4000"
    command: npm run dev  # This will start the app in development mode using nodemon

  # Production Service
  # app-prod:
  #   build:
  #     context: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   command: npm start  # Run the compiled JavaScript in production mode
