version: '3.8'

services:
  # Development Service
  app-dev:
    build:
      context: .
    volumes:
      - .:/usr/src/app:Z
    ports:
      - "4000:4000"
    networks:
      - gittracker_elk

networks:
  gittracker_elk:
    external: true
